### ISSUE TITLE
"Metoda płatności "PayU" jest niedostępna " gdy ponowna próba płatności przez Śledzenia Zamówienia Gość

### ISSUE THREAD

**Issue by hakeryk2** [PayU/plugin_prestashop#228]
Nie da się ponowić płatności dla zamówienia złożonego z konta gościa. Przy sprawdzaniu takiego zamówienia wyświetla się informacja po kliknięciu na "Ponownie zapłać przez Payu" komunikat "Metoda płatności "PayU" jest niedostępna".

Problem bierze się stąd, że w payment.php jest funkcja private function checkHasModuleActive(), która sprawdza 

`foreach (Module::getPaymentModules() as $module) {
            if ($module['name'] === 'payu') {
                $authorized = true;
                break;
            }`
Która przy sprawdzaniu zamówienia gościa zawsze zwróci false ponieważ Module::getPaymentModules() wtedy jest puste. Możnaby sprawdzić czy autoryzacja przejdzie poprzez 

` if (Module::isInstalled('payu')){
            $authorized = true;
        }`

Następnie w funkcji  private function postProcessRetryPayment() jest drugi warunek 
`  if (!Validate::isLoadedObject($this->order) || $this->order->id_customer != $this->context->customer->id) {
            Tools::redirect('index.php?controller=history');
        }`
Który zawsze przekieruje na powrót do logowania ponieważ w context nie ma customer->id ze względu na zamówienie gościa. Gdy testowo ten warunek usuniemy to płatność się odpali. Nie wiem jaki dodać warunek zabezpieczający który sprawdzi czy zamówienie jest akurat tego Klienta, ale chyba sam fakt, że ktoś się zalogował przez te dane jest potwierdzeniem. 

Gdyby ktoś ogarnął jakiś bezpieczniejszy sposób to może i goście sobie powtórzą płatność :)

**Comment by hakeryk2** [comment]
Ponawiam też w sumie zapytanie o dorobienie przycisku "Sprawdź ponownie status", ponieważ wiele osób narzeka, że w PayU Prestashop nie zawsze odbiera informację o zaakceptowaniu lub anulowaniu. W sklepie wisi status "płatność PayU rozpoczęta" i trzeba wchodzić na secure.payu.pl by sprawdzić ręcznie status transakcji. Gdyby był przycisk na stronie zamówienia w panelu admina i w hookAdminOrder który by triggerował ponowne sprawdzenie ułatwiłoby to znacznie pracę.

**Comment by regdos** [comment]
Co do problemu z kontem gościa to wkrótce postaramy się temu jakoś zaradzić.

>  PayU Prestashop nie zawsze odbiera informację o zaakceptowaniu lub anulowaniu.
Nie powinno być takiej sytuacji bo jeżeli Presta się wysypie (brak 200 przy odbiorze notyfikacji) to będzie ponowiona notyfikacja. Ostatnio dodaliśmy fix na 500 przy odbiorze notyfikacji. 
A sam przycisk to dobry pomysł. 

Planujemy pracę nad zmianą modelu ponowienia płatności, na taki który jest w naszym pluginie do Magento 2 i wtedy też ten przycisk byśmy dorabiali.

**Comment by regdos** [comment]
W wersji 3.0.15 - https://github.com/PayU/plugin_prestashop/releases/tag/v3.0.15 - problem został naprawiony.
