### ISSUE TITLE
Multistore zmiana domeny

### ISSUE THREAD

**Issue by kubapyla** [PayU/plugin_prestashop#229]
Cześć, mam MultiStore na Preście 1.6.1.18 na dwóch testowych adresach powiedzmy: 
**xxx.test.pl** i **yyy.test.pl**

Wszystko działało dopóki nie dokończyłem cesji domeny i zmieniłem adres sklepu **yyy.test.pl na mojanazwa.pl**, moduł PayU wyświetla teraz błąd:
```
Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /../modules/payu/payu.php on line 583

Parse error: syntax error, unexpected T_STRING in /../modules/payu/payu.php on line 583
```
pliku payu.php i blokuje dalsze wczytanie strony.

Podkreślam że mam skonfigurowaną bramkę REST do płatności w obu sklepach i z wykorzystaniem tymczasowych domen płatności działały normalnie

**Comment by regdos** [comment]
Jaką wersję PHP jest podpięta pod tą nową domenę?

**Comment by kubapyla** [comment]
Przepraszam za zamieszanie, problem rozwiązany, linuxpl.com po dodaniu nowej domeny w panelu włącza dla niej PHP 5.2 nigdzie o tym nie informując.
