### ISSUE TITLE
Problem z połączeniem cURL po aktualizacji obsługi TLS 

### ISSUE THREAD

**Issue by bazanowsky** [PayU/plugin_prestashop#232]
Witam, 

W związku z przejściem na obsługę protokołu TLS tylko w wersji 1.2 (http://developers.payu.com/pl/overview.html#encryption) na stronie naszego klienta wysypały się płatności - problem był jednak taki, że mimo że serwer (nazwa.pl xD) obsługiwał TLS 1.2 to domyślny protokół był inny przez co dostawałem error: `SSL connect error`

Rozwiązaniem problemu u klienta była modyfikacja pliku:
https://github.com/PayU/plugin_prestashop/blob/master/payu/tools/sdk/OpenPayU/HttpCurl.php

Po dopisaniu `curl_setopt ($ch, CURLOPT_SSLVERSION, 6);`  wszystko zaczęło smigać świetnie. 

Nie stworzyłem Pull Requestu, bo wydaje mi się, że takie rzeczy powinny być po stronie konfiguracji serwera a nie w kodzie wtyczki, aczkolwiek daję tutaj znać o problemie i rozwiązaniu - wy już dalej zdecydujecie co z tym faktem zrobić :)

**Comment by regdos** [comment]
W dokumentacji http://php.net/manual/en/function.curl-setopt.php nie zalecają jawnego ustawienia tej opcji  dlaego nie dodamy tej opcji.
