### ISSUE TITLE
Błąd w składni

### ISSUE THREAD

**Issue by Websited** [PayU/plugin_prestashop#236]
Po wgraniu modułu do /modules/ w back office pojawia się ostrzeżenie:

```
 2 błędów
     payu (błąd składni w /modules/payu/payu.php)
     payu (brakująca klasa w /modules/payu/payu.php)
```

Po włączeniu debugowania dostaję info o błędzie w składni:

```
Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /naturalsklep/classes/module/Module.php(1361) : eval()'d code on line 582

Parse error: syntax error, unexpected T_STRING in /naturalsklep/classes/module/Module.php(1361) : eval()'d code on line 582
```

**Comment by regdos** [comment]
Proszę podać wersję Presty.

**Comment by Websited** [comment]
Wersja 1.6.1.17

**Comment by regdos** [comment]
Po zainstalowaniu wersji presty 1.6.1.17 oraz pluginu 3.0.9 nie pojawiają się nam błędy w backoffice. 
Czy to była świeża instalacja czy aktualizacja istniejącego pluginu?

**Comment by Websited** [comment]
Odinstalowałem starszą wersję, usunąłem pliki z folderu plugins i zainstalowałem od nowa. Na poprzedniej wersji też ten problem był (plugin działał, potem przestał), aktualizacja nic nie pomogła, samo zainstalowanie pluginu do presty wyzwala taki błąd

**Comment by regdos** [comment]
Plugin w konfiguracji ma "need_instance" czyli nie powinno następować sprawdzenie eval'em(), który generuje ten błąd. 
Czy w konfiguracji Presty coś zostało zmienione?
Możemy spróbować na Pana instalacji naprawić ten problem. Jeżeli jest Pan zainteresowany to potrzebujemy danych dostępowych więc proszę o kontakt z BOK (tech@payu.pl) powołując się na to zgłoszenie.

**Comment by Websited** [comment]
Czy mogę w takim razie szukać przyczyny nie w module a w plikach samej presty?

**Comment by regdos** [comment]
Ciężko określić gdzie jest problem.
Na początek trzeba sprawdzić czy faktycznie w /naturalsklep/classes/module/Module.php w linii 1346 ( if (!class_exists($module, false)) {) wynikiem class_exists dla modułu payu jest false i jeżeli faktycznie jest to szukać dalej. Może jakiś inny plugin lub ustawienia powoduje, że nie tworzy się instancja pluginu PayU pomimo, że powinna. 
Proszę sprawdzić czy w plikach config*.xml jest need_instance ustawione na 1.
