### ISSUE TITLE
Call to undefined method PayU::getVersion()

### ISSUE THREAD

**Issue by brunogabuzomeu** [PayU/plugin_prestashop#237]
payu version = '3.0.9'

PHP Fatal error:  Call to undefined method PayU::getVersion() in /modules/payu/payu.php on line 147

**Comment by regdos** [comment]
Problem został już zgłoszony - https://github.com/PayU/plugin_prestashop/issues/234 

Proszę ponownie pobrać i zainstalować wersję 3.0.9
