### ISSUE TITLE
Błąd w szczegółach zamówienia. Presta 1.4.7.0

### ISSUE THREAD

**Issue by Erbik** [PayU/plugin_prestashop#240]
Błąd przy wejsciu w zamówienie, nie ładuje się do końca jak na screenie:
PrestaShop™ 1.4.7.0
Wgrana najnowsza wersja modułu, problem zaczał sie pojawiać od dzisiejszego ranka.

![image](https://user-images.githubusercontent.com/42570547/44391706-e099f700-a530-11e8-9155-a9716e1e15ee.png)

Żródło strony:
![image](https://user-images.githubusercontent.com/42570547/44392123-c14f9980-a531-11e8-9591-66f5ffc7c08e.png)

**Comment by regdos** [comment]
Nie wspieramy już pluginu dla presty 1.4 i 1.5
