### ISSUE TITLE
Identyfikator transakcji

### ISSUE THREAD

**Issue by garyfisher** [PayU/plugin_prestashop#241]
Witam mam wersje PrestaShop 1.6.1.4 + moduł PayU 3.0.11. Po aktualizacji do 3.0.11 mam problem że po płatności w panelu zamówienia nie uzupełnia pola Identyfikator transakcji.

W czym może być problem ?

Poniżej screen:
![image](https://user-images.githubusercontent.com/285517/44575593-a2007880-a78c-11e8-8999-968935bcca2c.png)

**Comment by regdos** [comment]
Z jakiej wersji byłą aktualizacja?

**Comment by regdos** [comment]
Dopisywanie PaymentId usunęliśmy w commicie https://github.com/PayU/plugin_prestashop/commit/bc5ee89c17aaf68d76f9b7678a86dfd500c413e6 ponieważ czasami powodowało to występowanie błędu 500 przy odbiorze notyfikacji. 
Przyjrzymy się czy nie da się tego przywrócić.

**Comment by regdos** [comment]
Przywróciliśmy dodawanie Identyfikator transakcji w commicie https://github.com/PayU/plugin_prestashop/commit/6b81cdd47a3a936bba48d91b854846f9c57802b8
Proszę o podmianę pliku payu.php i sprawdzenie czy wszystko jest ok.

**Comment by regdos** [comment]
@garyfisher czy testował Pan poprawkę?

**Comment by garyfisher** [comment]
> @garyfisher czy testował Pan poprawkę?

Sorry byłem na urlopie, dzisiaj wgrałem poprawkę na dniach odpisze czy działa.

**Comment by garyfisher** [comment]
> > @garyfisher czy testował Pan poprawkę?
> 
> Sorry byłem na urlopie, dzisiaj wgrałem poprawkę na dniach odpisze czy działa.

Poprawka działa, dziękuje bardzo za szybką reakcje.
