### ISSUE TITLE
Zakłamania wartości przelewów w panelu presty lub brak wartości.

### ISSUE THREAD

**Issue by bazanowsky** [PayU/plugin_prestashop#246]
Witam, 

Od kilku dni mamy w panelu presty w widoku pojedynczego zamowienia dziwne przeklamania i alerty, że przelana kwota nie jest pelna, ze np. zamiast przelac 300zl ktos przelal przez payu 200zl. I o ile przelewy sa poprawne - sprawdzilismy w panelu payu kwoty transakcji, to w prescie mielismy taki komunikat: 
http://prntscr.com/kvs89t 
http://prntscr.com/kvsapn

Co prawda, mielismy ostatnio burzliwa migracje miedzy serwerami, i przy migracji moglismy pominac cos w bazie danych, to zdziwilismy sie gdy przy nowych zamowieniach i nowych platnosciach, problem rowniez wystepowal. 

Blad z obrazka powyzej mielismy na wersji wtyczki 3.0.9. 

Zdecydowalem sie wiec zrobic aktualizacje - do wersji 3.0.13. 

Zrobilismy testowa platnosc, i ku mojemu zdziwieniu teraz kwota wcale sie nie pojawia. 
Widzimy status - ze platnosc jest wykonana, i jej status jest completed, ale nie widzimy kwoty przelewu: 
http://prntscr.com/kvsbim

Ostatni test pochodzi z wersji 3.0.13 wtyczki, 
Calosc jest na PrestaShop v1.7.2.4 

Pytanie moje brzmi: 
1. Czy to zamierzone ze teraz platnosci Payu nie beda sie pojawiac w platnosciach - i bedziemy widziec tylko ich status?
2. Jesli tak - czy planujecie przywrocic pokazywanie kwoty przelewu do widoku zamowienia? 
3. Gdzie powinienem szukac kodu odpowiedzialnego za dodanie nowej platnosci dla danego zamowienia? Probowalem samemu debugować problem, ale generalnie sie pogubilem :D 

Pozdrawiam serdecznie :)

**Comment by regdos** [comment]
W wersji 3.0.9 był problem przy odbiorze notyfikacji właśnie z dopisywaniem płatności. 
W wersji 3.0.13 dodaliśmy poprawiony mechanizm dopisywania płatności i powinno wszystko działać. 

Płatność jest automatycznie dopisywana przez prestę w momencie dodania FV (metoda changeIdOrderState w klasie OrderHistoryCore) a FV jest dodawane przy przejściu zamówienia w status, który jest traktowany jako płacony. 

W przypadku naszej wtyczki jest to w momencie odebrania notyfikacji COMPLETED (https://github.com/PayU/plugin_prestashop/blob/master/payu/payu.php#L1308) 
Następnie (2 linie dalej) do tej płątności jest dopisywany identyfikator PayU. 

Jeżeli będzie miał Pan problem z rozwiązaneim problemu proszę o kontakt z BOK podając dane sklepu i powołując się na to zgłoszenie.
