### ISSUE TITLE
VirusTotal reports VEX.Webshell form Bkav

### ISSUE THREAD

**Issue by rdy4ever** [PayU/plugin_prestashop#247]
https://www.virustotal.com/#/file/cfb2d2d703d7bee05c29c0786747bba7124145ce096b0b94670e876f6ecde8c8/detection

Hello. I have dowloaded your plugin (master branch) and run a virusttotal scan on the plugin. One scanner reports VEX.Webshell.

Can you check?

**Comment by regdos** [comment]
It is false positive.
